ADIFFICULTY_EASY = 'easy'
ADIFFICULTY_NORMAL = 'normal'
ADIFFICULTY_HARD = 'hard'
ADIFFICULTY_OVERKILL = 'overkill'
ARENA_DIFFICULTY_LEVELS = [
    ADIFFICULTY_EASY, ADIFFICULTY_NORMAL, ADIFFICULTY_HARD, ADIFFICULTY_OVERKILL]

GAME_STATE_STAGING = 'staging'
GAME_STATE_IN_BETWEEN = 'in-between'
GAME_STATE_ACTIVE = 'active'
GAME_STATE_FINISHED = 'finished'
GAME_STATES = [
    GAME_STATE_STAGING, GAME_STATE_IN_BETWEEN, GAME_STATE_ACTIVE,
    GAME_STATE_FINISHED
]
