
ITEM_TYPE_WEAPON = "weapon"
ITEM_TYPE_MELEE_WEAPON = "melee_weapon"
ITEM_TYPE_PART = "part"
ITEM_TYPE_COMMOD = "commodity"

ITEM_TYPES = [
    ITEM_TYPE_WEAPON, ITEM_TYPE_MELEE_WEAPON, ITEM_TYPE_PART,
    ITEM_TYPE_COMMOD
]
