from battlesnake.core.ansi import ANSI_HI_GREEN, ANSI_HI_CYAN, ANSI_HI_MAGENTA


ITEM_TYPE_WEAPON = "weapon"
ITEM_TYPE_MELEE_WEAPON = "melee_weapon"
ITEM_TYPE_PART = "part"
ITEM_TYPE_COMMOD = "commodity"

ITEM_TYPES = [
    ITEM_TYPE_WEAPON, ITEM_TYPE_MELEE_WEAPON, ITEM_TYPE_PART,
    ITEM_TYPE_COMMOD
]


BLUEPRINT_TYPE_STRUCTURAL = "structural"
BLUEPRINT_TYPE_ELECTRONICS = "electronics"
BLUEPRINT_TYPE_WEAPONRY = "weaponry"

BP_TYPE_COLORS = {
    BLUEPRINT_TYPE_STRUCTURAL: ANSI_HI_GREEN,
    BLUEPRINT_TYPE_ELECTRONICS: ANSI_HI_CYAN,
    BLUEPRINT_TYPE_WEAPONRY: ANSI_HI_MAGENTA,
}

BLUEPRINT_TYPES = [
    BLUEPRINT_TYPE_STRUCTURAL, BLUEPRINT_TYPE_ELECTRONICS,
    BLUEPRINT_TYPE_WEAPONRY,
]
